backend:
  name: github
  repo: icelandico/mesa-studio-web
  branch: redesign
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/assets
public_folder: /assets
show_preview_links: true

collections:
  - label: 'Sections'
    name: 'sections'
    files:
      - label: 'Studio section'
        name: 'studio'
        file: 'src/lib/content/sections/index.md'
        fields:
          - { label: Subtitle, name: studioSubtitle, widget: string }
          - { label: Image, name: studioImage, widget: image }
  - name: HomeGallery
    label: 'Home gallery'
    folder: 'src/lib/content/sectionHome/index.md'
    widget: list
    fields:
      - { name: image, label: Image, widget: image }
      - { name: alt, label: Alt, widget: string }
