backend:
  name: github
  repo: icelandico/mesa-studio-web
  branch: redesign
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/assets
public_folder: /assets
show_preview_links: true

collections:
  - label: 'Sekcje'
    name: 'sections'
    fields:
      - label: 'Home Sekcje'
        name: 'homeSections'
        file: 'src/lib/content/sections/index.md'
        fields:
          - { label: 'Studio podtytul', name: studioSubtitle, widget: string }
          - { label: 'Studio zdjecie', name: studioImage, widget: image }
          - {
              name: gallery,
              label: 'Home galeria'
              widget: image,
              choose_url: true,
              media_library: { config: { multiple: true, max_files: 10 } }
            }
